from typing import Protocol, runtime_checkable


@runtime_checkable
class ManaDisplay(Protocol):
    def show_value(self, value: int) -> None: ...
    def show_busy(self, value: int) -> None: ...
    def show_error(self) -> None: ...
    def show_off(self) -> None: ...
